export KONNECT_SERVER_URL="https://eu.api.konghq.com"
export TF_VAR_konnect_server_url="$KONNECT_SERVER_URL"
export VAULT_ADDR="http://localhost:8300"
export KONNECT_REGION="eu"
export TF_VAR_konnect_region="$KONNECT_REGION"