name: Load Environment Configuration
description: A composite action to load environment-specific configuration from YAML files.

inputs:
  environment:
    description: 'Deployment environment (dev, staging, prod)'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Load environment configuration
      id: load_config
      shell: bash
      env:
        ENV_FILE: .github/env/${{ inputs.environment }}.yaml
      run: |
        echo "Reading configuration from $ENV_FILE"
        COMMON_VARS_FILE=.github/env/.common/env.yaml
        CONFIG_VARS=$(yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1) | keys' $COMMON_VARS_FILE $ENV_FILE)

        for VAR in $CONFIG_VARS; do
          VALUE=$(yq eval-all "select(fileIndex == 0) * select(fileIndex == 1) | .${VAR}" $COMMON_VARS_FILE $ENV_FILE)
          UPPER_VAR=${VAR^^}
          echo "${UPPER_VAR}=${VALUE}" >> $GITHUB_ENV
          case $VAR in
            vault_addr|vault_token|konnect_region|env_name)
              TF_VAR_NAME="TF_VAR_${VAR}"
              echo "${TF_VAR_NAME}=${VALUE}" >> $GITHUB_ENV
              ;;
          esac
        done

        # Extra configuration for Konnect and Terraform
        KONNECT_REGION=$(yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1) | .konnect_region' $COMMON_VARS_FILE $ENV_FILE)
        KONNECT_SERVER_URL="https://$KONNECT_REGION.api.konghq.com"
        TF_VAR_KONNECT_PERSONAL_ACCESS_TOKEN=${{ secrets.KONNECT_PAT }}
        echo "KONNECT_SERVER_URL=$KONNECT_SERVER_URL" >> $GITHUB_ENV
        echo "TF_VAR_konnect_server_url=$KONNECT_SERVER_URL" >> $GITHUB_ENV
        echo "TF_VAR_environment=${{ inputs.environment }}" >> $GITHUB_ENV
