name: Deploy Observability Tools
on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace'
        type: string
        default: 'kong-observability'
      control_plane_name:
        description: 'The name of the control plane to configure'
        type: string
        required: true
      konnect_server_url:
        description: 'Konnect server URL'
        type: string
        default: https://eu.api.konghq.com
      action:
        description: 'Action to perform'
        required: true
        type: choice
        default: 'provision'
        options:
          - 'provision'
          - 'destroy'
      # Observability stack to deploy
      # Supported values: datadog, grafana, dynatrace
      # Grafana stack includes Loki, Tempo, Prometheus, Fluent Bit
      # Datadog stack needs DD_API_KEY secret
      # Dynatrace stack needs DT_API_TOKEN and optional DT_DATA_INJEST_TOKEN secrets
      observability_stack:
        description: 'Observability stack to deploy'
        required: true
        type: string
        default: 'datadog'
jobs: 
  prepare:
    runs-on: ubuntu-latest

    env:
      DECK_CONFIG_NAMESPACE: ${{ inputs.namespace }}
      KUBECONFIG: /.kube/config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: kong/setup-deck@v1

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure global observability plugins
        if: ${{ inputs.action == 'deploy' }}
        run: |

          # Add Global observability plugins to the Kong Gateway configuration depending on the observability stack
          cat kong.yaml | deck file add-plugins plugins/${{ inputs.observability_stack }}/* -o kong.yaml
          
          # Apply patches to the Kong Gateway configuration depending on the observability stack
          cat kong.yaml | deck file patch patches/${{ inputs.observability_stack }}/* -o kong.yaml
          
          # Apply the Kong Gateway configuration
          deck gateway sync kong.yaml  \
            --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ secrets.KONNECT_PAT }} \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}"

        working-directory: ${{ github.workspace }}/examples/observability/

      - name: kubectl use context
        run: |
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}
          
      - name: Create Kong observability namespace if not exists
        if: ${{ inputs.action == 'deploy' }}
        run: |
          kubectl create namespace $DECK_CONFIG_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Required Helm Repositories
        if: ${{ inputs.action == 'deploy' }}
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add fluent https://fluent.github.io/helm-charts
          helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
          helm repo add datadog https://helm.datadoghq.com
          
          helm repo add jetstack https://charts.jetstack.io --force-update
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts

      #####################################################################
      ## DYNATRACE STACK DEPLOYMENT                                      ##
      #####################################################################   

      - name: Deploy Dynatrace OneAgent Operator
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'dynatrace'}}
        run: |

          # Check if the DT_API_TOKEN secret is set
          if [ -z "${{ secrets.DT_API_TOKEN }}" ]; then
            echo "DT_API_TOKEN secret is required for Dynatrace OneAgent Operator deployment"
            exit 1
          fi
          
          #Install cert manager
          helm upgrade --install \
            cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.16.2 \
            --set crds.enabled=true

          # Install Opentelemetry Operator
          helm upgrade --install opentelemetry-operator open-telemetry/opentelemetry-operator \
            --namespace opentelemetry-operator-system \
            --create-namespace \
            --wait \
            --set "manager.collectorImage.repository=otel/opentelemetry-collector-k8s" \
            --set admissionWebhooks.certManager.enabled=true

          # Create Dynatrace API credentials secret
          kubectl create secret generic dynatrace-endpoint -n kong --from-literal=dt-endpoint='https://rcr22892.live.dynatrace.com/api/v2/otlp' --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic dynatrace-access-token -n kong --from-literal=dt-access-token='${{ secrets.DT_API_TOKEN }}' --dry-run=client -o yaml | kubectl apply -f -

          # Create rbac
          # kubectl apply -f ${{ github.workspace }}/k8s/dynatrace/rbac.yaml
          
          # Deploy the OpenTelemetry Collector
          kubectl apply -f ${{ github.workspace }}/k8s/dynatrace/otelcollector-dynatrace.yaml
      
      
      #####################################################################
      ## DATADOG STACK DEPLOYMENT                                        ##
      #####################################################################      
      - name: Deploy Datadog Agent
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'datadog'}}
        run: |

          # Check if the DD_API_KEY secret is set
          if [ -z "${{ secrets.DD_API_KEY }}" ]; then
            echo "DD_API_KEY secret is required for Datadog stack deployment"
            exit 1
          fi

          kubectl create secret generic datadog-secret --from-literal api-key=${{ secrets.DD_API_KEY }} -n $DECK_CONFIG_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade --install datadog-agent datadog/datadog \
            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/datadog/values.yaml

      #####################################################################
      ## GRAFANA STACK DEPLOYMENT                                        ##
      #####################################################################

      - name: Deploy Prometeus operator
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana' }}
        run: |
          helm upgrade --install kong-prometheus prometheus-community/kube-prometheus-stack \
            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/prom/values.yaml

      - name: Create Grafana Kong dashboard ConfigMap
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
        run: |
          kubectl -n $DECK_CONFIG_NAMESPACE create cm grafana-kong-official --from-file=${{ github.workspace }}/k8s/grafana/dashboards/kong-official.json --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n $DECK_CONFIG_NAMESPACE label cm grafana-kong-official grafana_dashboard="1"

      - name: Deploy Grafana tempo
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
        run: |
          helm upgrade --install tempo grafana/tempo -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/tempo/values.yaml

      - name: Deploy Loki stack
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
        run: |
          helm upgrade --install loki grafana/loki-stack \
            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/loki/values.yaml

      - name: Deploy fluent-bit
        if: ${{ inputs.action == 'deploy' && inputs.observability_stack == 'grafana'}}
        run: |
          helm upgrade --install fluent-bit fluent/fluent-bit \
            -n $DECK_CONFIG_NAMESPACE --values ${{ github.workspace }}/k8s/fluent-bit/values.yaml

      ##############################################################################
      ## DESTROY OBSERVABILITY STACK                                              ##
      ##############################################################################

      - name: Destroy Observability Stack
        if: ${{ inputs.action == 'destroy' }}
        run: |
          helm uninstall kong-prometheus -n $DECK_CONFIG_NAMESPACE || true
          helm uninstall tempo -n $DECK_CONFIG_NAMESPACE || true
          helm uninstall loki -n $DECK_CONFIG_NAMESPACE || true
          helm uninstall fluent-bit -n $DECK_CONFIG_NAMESPACE || true
          
          helm uninstall datadog-agent -n $DECK_CONFIG_NAMESPACE || true
          kubectl delete secret datadog-secret || true

          helm uninstall dynatrace-operator -n $DECK_CONFIG_NAMESPACE || true
          kubectl delete secret dynatrace || true
          kubectl delete -f ${{ github.workspace }}/k8s/dynatrace/otelcollector-dynatrace.yaml || true
          kubectl delete -f k8s/dynatrace/rbac.yaml || true

      - name: Destroy Grafana Kong dashboard ConfigMap
        if: ${{ inputs.action == 'destroy' }}
        run: |
          kubectl -n $DECK_CONFIG_NAMESPACE delete cm grafana-kong-official || true

      - name: Destroy Kong observability namespace
        if: ${{ inputs.action == 'destroy' }}
        run: |
          kubectl delete namespace $DECK_CONFIG_NAMESPACE || true
      
      - name: Destroy Kong Gateway configuration
        if: ${{ inputs.action == 'destroy' }}
        run: |
          deck gateway reset --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ secrets.KONNECT_PAT }} \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" \
            --select-tag=observability \
            --select-tag=platform_team \
            --force
        working-directory: ${{ github.workspace }}/examples/observability/
      
      