name: Provision Konnect Team resources

on:
  workflow_call:
    inputs:
      config:
        description: 'Path to the provisioning config file'
        type: string
        required: true
      action:
        description: 'Action to perform'
        type: string
        default: 'provision'
      environment:
        description: 'Environment to provision'
        type: string
        default: 'dev'

jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment configuration
        uses: ./.github/actions/load-config
        with:
          environment: ${{ inputs.environment }}
        env:
          KONNECT_PAT: ${{ secrets.KONNECT_PAT }}

      - name: Provision Konnect Resources
        uses: ./.github/actions/konnect-team-resources
        with:
          action: ${{ inputs.action }}
          config: $( cat ${{ github.workspace }}/${{ inputs.config }} | jq -r . )
          vault_token: ${{ secrets.VAULT_TOKEN }}
          system_account_token: ${{ secrets.KONNECT_PAT }}
          s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
          s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
          konnect_token: ${{ secrets.KONNECT_PAT }}